### ISSUE TITLE
after update to 1.4, XF.Material.Droid.Material.Init failed.

### ISSUE THREAD

**Issue by kenchan97** [contrix09/XF-Material-Library#137]
**Describe the bug**
Error CS0234: The type or namespace name 'Droid' does not exist in the namespace 'XF.Material' (are you missing an assembly reference?) (CS0234)

**To Reproduce**
create a new forms App. in Mac VStudio
add XF.Material from nuget to shared project
add " XF.Material.Droid.Material.Init(this, savedInstanceState); "
build it.
error.....

**Comment by contrix09** [comment]
Hi, please refer to this [issue](https://github.com/contrix09/XF-Material-Library/issues/99).
